"""truncate datetime to second

Revision ID: 2acb82183b0a
Revises: ff5405726a70
Create Date: 2026-06-06 17:15:13.064615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2acb82183b0a'
down_revision: Union[str, Sequence[str], None] = 'ff5405726a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - change default to date_trunc('second', now())."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faq_records', 'created_at',
        existing_type=sa.DateTime(timezone=False),
        type_=sa.DateTime(timezone=False),
        existing_nullable=False,
        server_default=sa.text("date_trunc('second', now())"),
        schema='knowledge'
    )
    op.alter_column('faq_records', 'updated_at',
        existing_type=sa.DateTime(timezone=False),
        type_=sa.DateTime(timezone=False),
        existing_nullable=False,
        server_default=sa.text("date_trunc('second', now())"),
        schema='knowledge'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - revert default to func.now()."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faq_records', 'created_at',
        existing_type=sa.DateTime(timezone=False),
        type_=sa.DateTime(timezone=False),
        existing_nullable=False,
        server_default=sa.text('now()'),
        schema='knowledge'
    )
    op.alter_column('faq_records', 'updated_at',
        existing_type=sa.DateTime(timezone=False),
        type_=sa.DateTime(timezone=False),
        existing_nullable=False,
        server_default=sa.text('now()'),
        schema='knowledge'
    )
    # ### end Alembic commands ###