"""add default for created_by and updated_by

Revision ID: 386a99a437ba
Revises: 6559254607eb
Create Date: 2026-06-06 16:03:45.671347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386a99a437ba'
down_revision: Union[str, Sequence[str], None] = '6559254607eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Downgrade schema - remove default values."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faq_records', 'created_by', server_default='system', schema='knowledge')
    op.alter_column('faq_records', 'updated_by', server_default='system', schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - add default values."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faq_records', 'created_by', server_default=None, schema='knowledge')
    op.alter_column('faq_records', 'updated_by', server_default=None, schema='knowledge')
    # ### end Alembic commands ###
