"""init faq table

Revision ID: 484a044941eb
Revises: 0c08c92acfca
Create Date: 2026-06-06 11:51:39.606496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484a044941eb'
down_revision: Union[str, Sequence[str], None] = '0c08c92acfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_records',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键'),
    sa.Column('question', sa.String(length=1024), nullable=False, comment='问题文本'),
    sa.Column('answer', sa.Text(), nullable=False, comment='答案文本'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.String(length=20), nullable=False, comment='创建人'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.String(length=20), nullable=False, comment='更新人'),
    sa.Column('ver', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='查看次数'),
    sa.Column('knowledge_type', sa.Enum('BC', 'OC', 'SC', name='knowledge_type'), nullable=False, comment='知识类型'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('vector_id', sa.String(length=64), nullable=True, comment='向量库 Point ID'),
    sa.Column('embedding_status', sa.Enum('PENDING', 'INDEXED', 'FAILED', name='embedding_status'), nullable=False, comment='向量状态: pending/indexed/failed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vector_id'),
    schema='knowledge'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq_records', schema='knowledge')
    # ### end Alembic commands ###
