"""add Index

Revision ID: 6559254607eb
Revises: 484a044941eb
Create Date: 2026-06-06 14:08:46.409426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6559254607eb'
down_revision: Union[str, Sequence[str], None] = '484a044941eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - add indexes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_embedding_status', 'faq_records', ['embedding_status'], unique=False, schema='knowledge')
    op.create_index('idx_is_deleted', 'faq_records', ['is_deleted'], unique=False, schema='knowledge')
    op.create_index('idx_is_enabled', 'faq_records', ['is_enabled'], unique=False, schema='knowledge')
    op.create_index('idx_knowledge_type', 'faq_records', ['knowledge_type'], unique=False, schema='knowledge')
    op.create_index('idx_vector_id', 'faq_records', ['vector_id'], unique=False, schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vector_id', table_name='faq_records', schema='knowledge')
    op.drop_index('idx_knowledge_type', table_name='faq_records', schema='knowledge')
    op.drop_index('idx_is_enabled', table_name='faq_records', schema='knowledge')
    op.drop_index('idx_is_deleted', table_name='faq_records', schema='knowledge')
    op.drop_index('idx_embedding_status', table_name='faq_records', schema='knowledge')
    op.drop_table('faq_records', schema='knowledge')
    # ### end Alembic commands ###
