"""add user model

Revision ID: bcbb7126ed8a
Revises: 2acb82183b0a
Create Date: 2026-06-07 22:15:09.101128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbb7126ed8a'
down_revision: Union[str, Sequence[str], None] = '2acb82183b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("date_trunc('second', now())"), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("date_trunc('second', now())"), nullable=False, comment='更新时间'),
    sa.Column('ver', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('account', sa.String(length=30), nullable=False, comment='账号'),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('is_frozen', sa.Boolean(), nullable=False, comment='是否冻结'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    schema='auth'
    )
    op.create_index('idx_account', 'user', ['account'], unique=False, schema='auth')
    op.create_index('idx_id', 'user', ['id'], unique=False, schema='auth')
    op.create_index('idx_is_deleted', 'user', ['is_deleted'], unique=False, schema='auth')
    op.create_index('idx_phone_number', 'user', ['phone_number'], unique=False, schema='auth')
    op.create_index('idx_id', 'faq_records', ['id'], unique=False, schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_id', table_name='faq_records', schema='knowledge')
    op.drop_table('faq_records', schema='knowledge')
    op.drop_index('idx_phone_number', table_name='user', schema='auth')
    op.drop_index('idx_is_deleted', table_name='user', schema='auth')
    op.drop_index('idx_id', table_name='user', schema='auth')
    op.drop_index('idx_account', table_name='user', schema='auth')
    op.drop_table('user', schema='auth')
    # ### end Alembic commands ###
