"""add api_key table

Revision ID: c63a2c055015
Revises: bcbb7126ed8a
Create Date: 2026-06-08 17:58:06.912670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63a2c055015'
down_revision: Union[str, Sequence[str], None] = 'bcbb7126ed8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='备注名称（如"XXX平台"）'),
    sa.Column('api_key', sa.String(length=64), nullable=False, comment='公开的 API Key'),
    sa.Column('secret', sa.String(length=255), nullable=False, comment='API Secret（明文存储，仅创建时返回）'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("date_trunc('second', now())"), nullable=False, comment='创建时间'),
    sa.Column('created_by', sa.String(length=20), nullable=False, comment='创建人'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    schema='auth'
    )
    op.create_index('idx_api_key', 'api_keys', ['api_key'], unique=False, schema='auth')
    op.create_index('idx_api_keys_is_deleted', 'api_keys', ['is_deleted'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_api_keys_is_deleted', table_name='api_keys', schema='auth')
    op.drop_index('idx_api_key', table_name='api_keys', schema='auth')
    op.drop_table('api_keys', schema='auth')
    # ### end Alembic commands ###
