"""change datetime to timezone false

Revision ID: ff5405726a70
Revises: 386a99a437ba
Create Date: 2026-06-06 16:57:34.540582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5405726a70'
down_revision: Union[str, Sequence[str], None] = '386a99a437ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - change datetime to timezone=False."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faq_records', 'created_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DateTime(timezone=False),
                    existing_nullable=False,
                    existing_server_default=sa.text('now()'),
                    schema='knowledge'
                    )
    op.alter_column('faq_records', 'updated_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DateTime(timezone=False),
                    existing_nullable=False,
                    existing_server_default=sa.text('now()'),
                    schema='knowledge'
                    )



def downgrade() -> None:
    """Upgrade schema - change datetime to timezone=True."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faq_records', 'created_at',
                    existing_type=sa.DateTime(timezone=False),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False,
                    existing_server_default=sa.text('now()'),
                    schema='knowledge'
                    )
    op.alter_column('faq_records', 'updated_at',
                    existing_type=sa.DateTime(timezone=False),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False,
                    existing_server_default=sa.text('now()'),
                    schema='knowledge'
                    )
    # ### end Alembic commands ###
